### PR TITLE
6 updates

### PR DESCRIPTION
**Pull request by hexadecimal233**
Moved JourneyMap/XaeroMap Tab settings into a module
Removed Noclip (Wont work on servers)
Simplify MapIntegration mixins
Remove Asm Init code in MixinPlugin
Use Modules.get() instead of getting module in MeteorPlus instance 
Fix xaero map integration being loaded even it does not exist in mod folder

### CODE REVIEW

**Review by Nekiplay — COMMENTED** [review]
why module and not Tab?
It will be better if each minicard has its own tab, as the settings for them are different

**Comment by hexadecimal233** [comment]
With tabs, if you installed both of the minimap mods, the bar will probably be out of the screen


Also, the old configuration system seems bad, need to do multiple checks and converts before getting the final boolean value

**Comment by Nekiplay** [comment]
> With tabs, if you installed both of the minimap mods, the bar will probably be out of the screen
> 
> Also, the old configuration system seems bad, need to do multiple checks and converts before getting the final boolean v

I don't think anyone would use 2 mini maps as they would only get in each other's way, and they would take up more space of the loaded chunks

**Comment by Nekiplay** [comment]
> With tabs, if you installed both of the minimap mods, the bar will probably be out of the screen
> 
> Also, the old configuration system seems bad, need to do multiple checks and converts before getting the final boolean value

I checked if the meteor client has tab overflow and it doesn't, but there aren't many tabs, I'll have to try to solve this problem.
image

**Comment by hexadecimal233** [comment]
The only Reason I changed this, is TAB configurationneeds more steps than a module (also slower imo)

**Comment by Nekiplay** [comment]
> The only Reason I changed this, is TAB configurationneeds more steps than a module (also slower imo)

In what way is it slower?
Yes, and in general, mod settings are rarely changed after customizing them

**Comment by Nekiplay** [comment]
Replacing tabs with modules don't look appropriate especially in one group

**Comment by hexadecimal233** [comment]
Closing due to conflicts

**Comment by hexadecimal233** [comment]
Closing due to conflicts

**Pull request closed without merging**
